name: SonarCloud Issues Sync

on:
  workflow_dispatch:
#   pull_request:
#     branches: [ main ]

jobs:
  sonarcloud_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync SonarCloud Issues
        uses: Gorton218/sonarqube-to-github-issue-sync@fix_call
        with:
          sonar_project: my-org_my-project
        secrets:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
