name: SonarCloud Issues Sync

on:
  workflow_dispatch:
#   pull_request:
#     branches: [ main ]

jobs:
  sonarcloud_sync:
    uses: Gorton218/sonarqube-to-github-issue-sync@main
    with:
        sonar_project: my-org_my-project
    secrets:
        sonar_token: ${{ secrets.SONAR_TOKEN }}
