name: SonarCloud Issues Sync

on:
  workflow_dispatch:
#   pull_request:
#     branches: [ main ]

jobs:
  sonarcloud_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync SonarCloud Issues
        uses: Gorton218/sonarqube-to-github-issue-sync@fix_call
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          sonar_project: Gorton218_puppetfile-depgraph
