name: SonarCloud Issues Sync

on:
  workflow_dispatch:
#   pull_request:
#     branches: [ main ]

jobs:
  sonarcloud_sync:
    runs-on: ubuntu-latest
    permissions:
      issues: write      # Required to create and close issues
      contents: read     # Required to checkout code
    steps:
      - name: Sync SonarCloud Issues
        uses: Gorton218/sonarqube-to-github-issue-sync@fix_call
        with:
            sonar_project: Gorton218_puppetfile-depgraph
            sonar_token: ${{ secrets.SONAR_TOKEN }}
